apiVersion: v1
kind: Service
metadata:
  labels:
    service: todo-app-api
  name: todo-app-api
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      port: 3001
      targetPort: 3001
  selector:
    service: todo-app-api

